// <auto-generated />
namespace EP.IdentityIsolation.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class identyIsolation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identyIsolation));
        
        string IMigrationMetadata.Id
        {
            get { return "201703262132143_identyIsolation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
